import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Synapsis Blog",
  description: "Generated by Rizal Alfandi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto max-w-screen-lg">
          <Header />
          <div className="px-2 pt-4 pb-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
